### ISSUE TITLE
Set up domain erntehelfer-suche.de

### ISSUE THREAD

**Issue by ManuelB** [ManuelB/erntehelfer-suche.de#1]

**Comment by freemin7** [comment]
Domain is registriert:
`whois erntehelfer-suche.de
[Querying whois.denic.de]
[whois.denic.de]
% Restricted rights.
% 
% Terms and Conditions of Use
% 
% The above data may only be used within the scope of technical or
% administrative necessities of Internet operation or to remedy legal
% problems.
% The use for other purposes, in particular for advertising, is not permitted.
% 
% The DENIC whois service on port 43 doesn't disclose any information concerning
% the domain holder, general request and abuse contact.
% This information can be obtained through use of our web-based whois service
% available at the DENIC website:
% http://www.denic.de/en/domains/whois-service/web-whois.html
% 
% 

Domain: erntehelfer-suche.de
Nserver: ns-1096.awsdns-09.org
Nserver: ns-111.awsdns-13.com
Nserver: ns-1878.awsdns-42.co.uk
Nserver: ns-716.awsdns-25.net
Status: connect
Changed: 2020-03-20T15:34:48+01:00
`

**Comment by ManuelB** [comment]
@freemin7 ja, von mir ;-)

**Comment by freemin7** [comment]
Ich dachte mir das schon
